import os.path

from ..constants import ANALYSIS_DIR

DEVIATION_DIR = os.path.join(ANALYSIS_DIR, 'deviation')
INTERPOLATED_DEVIATION_FILENAME = 'interpolated_deviation_{}_{}.npy'

# INTERPOLATED_DEVIATION_INTERPOLATOR_SETUP = (0.1, 2, 0.2)
# INTERPOLATED_DEVIATION_LSM_TMM_INTERPOLATOR_SETUP = (0.1, 1, 0)

